name: Setup PR for code review

on:
  pull_request_target:
    types: [opened, reopened]

permissions: write-all

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Parsing your PR title for lab number
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          SUB='Лаб.'
          for VAR in 1 2 3 4 5
          do
            if echo "$TITLE" | grep -iqE "$SUB *$VAR"; then
                echo "LABEL=Lab $VAR" >> "$GITHUB_ENV"
                break
            fi
          done
          for VAR in 6211 6212 6213 6214
          do
              if (echo $TITLE | grep -iqF "$VAR" ); then
                  echo "GROUP=$VAR" >> "$GITHUB_ENV"
                  break
              fi      
          done

      - name: Checking your lab number
        run: |
          if [[ -z $LABEL ]]; then
              echo "ERROR: Unable to determine the lab number from the PR title."
              exit 1
          fi
          echo "SUCCESS: Lab number was parsed correctly - $LABEL"

      - name: Checking your group number
        run: |
          if [[ -z $GROUP ]]; then
              echo "ERROR: Unable to determine the group number from the PR title."
              exit 1
          fi
          echo "SUCCESS: Group number was parsed correctly - $GROUP"

      - name: Setting PR labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            $LABEL
            $GROUP
            In progress

      - name: Setting reviewer
        if: env.GROUP == '6214'
        uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
        with:
          reviewers: "mxwrlld"
          token: ${{ secrets.GITHUB_TOKEN }}
