name: Обновление меток при апруве PR

on:
  pull_request_review:
    types: [submitted]

permissions: write-all

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Удаление метки "IN PROGRESS"
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            IN PROGRESS

      - name: Добавление метки "APPROVED"
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            APPROVED